package com.weiki.prismbackend.service;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfWriter;
import com.weiki.prismbackend.model.RiskItem;
import com.weiki.prismbackend.model.entity.Review;
import org.springframework.stereotype.Service;

import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.util.List;

@Service
public class ReviewExportService {

    private final ReviewService reviewService;

    public ReviewExportService(ReviewService reviewService) {
        this.reviewService = reviewService;
    }

    /**
     * 将 Review 导出为 Markdown 格式字符串。
     */
    public String exportMarkdown(Review review) {
        List<RiskItem> risks = reviewService.parseRisks(review.getRisksJson());
        List<String> suggestions = reviewService.parseSuggestions(review.getSuggestionsJson());
        int healthScore = HealthScoreCalculator.calculate(risks);
        String mergeAdvice = HealthScoreCalculator.mergeAdvice(healthScore);

        StringBuilder sb = new StringBuilder();
        sb.append("# PRism Code Review Report\n\n");
        sb.append("## 基本信息\n\n");
        sb.append("| 项目 | 内容 |\n");
        sb.append("|------|------|\n");
        sb.append("| PR 标题 | ").append(nullSafe(review.getPrTitle())).append(" |\n");
        sb.append("| 作者 | ").append(nullSafe(review.getAuthor())).append(" |\n");
        sb.append("| 仓库 | ").append(nullSafe(review.getGhRepo())).append(" |\n");
        sb.append("| PR 链接 | ").append(nullSafe(review.getPrUrl())).append(" |\n");
        sb.append("| 健康分 | ").append(healthScore).append(" / 100 |\n");
        sb.append("| 合并建议 | ").append(nullSafe(mergeAdvice)).append(" |\n");
        sb.append("\n");

        sb.append("## 变更摘要\n\n");
        sb.append(nullSafe(review.getSummary())).append("\n\n");

        if (!risks.isEmpty()) {
            sb.append("## 风险项 (").append(risks.size()).append(")\n\n");
            for (int i = 0; i < risks.size(); i++) {
                RiskItem risk = risks.get(i);
                sb.append("### ").append(i + 1).append(". [").append(risk.getLevel()).append("] ");
                sb.append(risk.getDescription()).append("\n\n");
                sb.append("- **文件**: ").append(nullSafe(risk.getFile()));
                if (risk.getLine() != null) {
                    sb.append(" (L").append(risk.getLine()).append(")");
                }
                sb.append("\n");
                sb.append("- **置信度**: ").append(risk.getConfidence()).append("\n");
                if (risk.getSuggestedFix() != null && !risk.getSuggestedFix().isBlank()) {
                    sb.append("- **建议修复**: ").append(risk.getSuggestedFix()).append("\n");
                }
                sb.append("\n");
            }
        }

        if (!suggestions.isEmpty()) {
            sb.append("## 改进建议\n\n");
            for (String s : suggestions) {
                sb.append("- ").append(s).append("\n");
            }
            sb.append("\n");
        }

        sb.append("---\n");
        sb.append("*Generated by PRism AI Code Review Platform*\n");
        return sb.toString();
    }

    /**
     * 将 Review 导出为 PDF 字节数组。
     */
    public byte[] exportPdf(Review review) {
        List<RiskItem> risks = reviewService.parseRisks(review.getRisksJson());
        List<String> suggestions = reviewService.parseSuggestions(review.getSuggestionsJson());
        int healthScore = HealthScoreCalculator.calculate(risks);
        String mergeAdvice = HealthScoreCalculator.mergeAdvice(healthScore);

        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4, 50, 50, 50, 50);
            PdfWriter.getInstance(document, baos);
            document.open();

            // 尝试加载中文字体，fallback 到 Helvetica
            Font titleFont;
            Font headingFont;
            Font bodyFont;
            Font boldFont;
            try {
                BaseFont chinese = BaseFont.createFont("STSong-Light", "UniGB-UCS2-H", BaseFont.NOT_EMBEDDED);
                titleFont = new Font(chinese, 18, Font.BOLD);
                headingFont = new Font(chinese, 14, Font.BOLD);
                bodyFont = new Font(chinese, 11, Font.NORMAL);
                boldFont = new Font(chinese, 11, Font.BOLD);
            } catch (Exception e) {
                titleFont = new Font(Font.HELVETICA, 18, Font.BOLD);
                headingFont = new Font(Font.HELVETICA, 14, Font.BOLD);
                bodyFont = new Font(Font.HELVETICA, 11, Font.NORMAL);
                boldFont = new Font(Font.HELVETICA, 11, Font.BOLD);
            }

            // Title
            Paragraph title = new Paragraph("PRism Code Review Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            // Basic info
            document.add(new Paragraph("Basic Info", headingFont));
            document.add(new Paragraph("PR Title: " + nullSafe(review.getPrTitle()), bodyFont));
            document.add(new Paragraph("Author: " + nullSafe(review.getAuthor()), bodyFont));
            document.add(new Paragraph("Repository: " + nullSafe(review.getGhRepo()), bodyFont));
            document.add(new Paragraph("Health Score: " + healthScore + " / 100", bodyFont));
            document.add(new Paragraph("Merge Advice: " + nullSafe(mergeAdvice), bodyFont));
            document.add(new Paragraph(" "));

            // Summary
            document.add(new Paragraph("Summary", headingFont));
            document.add(new Paragraph(nullSafe(review.getSummary()), bodyFont));
            document.add(new Paragraph(" "));

            // Risks
            if (!risks.isEmpty()) {
                document.add(new Paragraph("Risks (" + risks.size() + ")", headingFont));
                for (int i = 0; i < risks.size(); i++) {
                    RiskItem risk = risks.get(i);
                    String riskLine = (i + 1) + ". [" + risk.getLevel() + "] " + risk.getDescription();
                    document.add(new Paragraph(riskLine, boldFont));
                    String fileLine = "   File: " + nullSafe(risk.getFile());
                    if (risk.getLine() != null) fileLine += " (L" + risk.getLine() + ")";
                    document.add(new Paragraph(fileLine, bodyFont));
                    if (risk.getSuggestedFix() != null && !risk.getSuggestedFix().isBlank()) {
                        document.add(new Paragraph("   Fix: " + risk.getSuggestedFix(), bodyFont));
                    }
                }
                document.add(new Paragraph(" "));
            }

            // Suggestions
            if (!suggestions.isEmpty()) {
                document.add(new Paragraph("Suggestions", headingFont));
                for (String s : suggestions) {
                    document.add(new Paragraph("• " + s, bodyFont));
                }
            }

            document.close();
            return baos.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF", e);
        }
    }

    private String nullSafe(String s) {
        return s == null ? "" : s;
    }
}
